brew "atlas"
brew "gh"
brew "git"
brew "go"
brew "go-task"
brew "golangci-lint"
brew "tfenv"

cask "1password"
cask "docker"
cask "freedom"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "microsoft-edge"
cask "postman"
cask "raycast"
cask "sequel-ace"
cask "slack"
cask "visual-studio-code"
cask "warp"

mas "Xcode", id: 497799835
