tap "hashicorp/tap"

brew "git"
brew "go"
brew "awscli"
brew "llvm"
brew "hashicorp/tap/terraform"

cask "google-chrome"
cask "google-cloud-sdk"
cask "zoom"
cask "visual-studio-code"
cask "slack"
cask "docker"
cask "1password"
cask "discord"
cask "warp"
