brew "git"
brew "go"
brew "node"
brew "awscli"
brew "llvm"

cask "google-chrome"
cask "google-cloud-sdk"
cask "zoom"
cask "visual-studio-code"
cask "slack"
cask "docker"
cask "1password"
cask "iterm2"